### ISSUE TITLE
UI Component XML configuration - 404 link

### ISSUE THREAD

**Issue by denistrator** [AdobeDocs/commerce-frontend-core#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

https://developer.adobe.com/commerce/frontend-core/ui-components/concepts/xml-configuration/
"Basic elements" section, "component" row, "[basic attributes](https://developer.adobe.com/commerce/frontend-core/basic-attributes.md)" link is 404

**Comment by jeff-matthews** [comment]
Fixed in #125
