### ISSUE TITLE
Css issue

### ISSUE THREAD

**Issue by farzeen-cloud** [AdobeDocs/commerce-frontend-core#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Text is overriding right container
![image](https://github.com/AdobeDocs/commerce-frontend-core/assets/80716853/87f62623-7bf4-4cc6-98e9-9b11c6c5ad6d)

### Actual behavior

flexbox need to be correctly assigned.

### Steps to reproduce

flexbox need to be correctly assigned.

### Environment

- Browser: Chrome
- OS: Ubuntu 20

**Comment by jeff-matthews** [comment]
Thanks for letting us know @farzeen-cloud. This is an issue with the theme we use ([adobe/aio-theme](https://github.com/adobe/aio-theme)) and should technically be reported there. I'll leave this open for now though.
