### ISSUE TITLE
incorrect link in left menu

### ISSUE THREAD

**Issue by RetroProgrammist** [AdobeDocs/commerce-frontend-core#62]
Issue in /src/pages/ui-components/components/dynamic-rows.md
Hello, in left menu "DynamicRows" point menu with incorrect link

**Comment by jeff-matthews** [comment]
Thanks for the report @RetroProgrammist.

Here's the page that it should be linking to: https://developer.adobe.com/commerce/frontend-core/ui-components/components/dynamic-rows/.

The [navigation link](https://github.com/AdobeDocs/commerce-frontend-core/blob/main/src/data/navigation/sections/ui_components.js#L162) should be updated to:

```
        {
          title: "DynamicRows",
          path: "/ui-components/components/dynamic-rows/"
        },
```

Please feel free to submit a pull request to fix it.

**Comment by dobooth** [comment]
This has been fixed.
