### ISSUE TITLE
Example Image is wrong

### ISSUE THREAD

**Issue by vishnunathkrs** [AdobeDocs/commerce-frontend-core#66]
Issue in /src/pages/guide/translations/practice.md

https://github.com/AdobeDocs/commerce-frontend-core/blob/main/src/pages/guide/translations/practice.md

Source page: https://developer.adobe.com/commerce/frontend-core/guide/translations/practice/

Please update the image mentioned in example. it's wrongly updated

**Comment by shrielenee** [comment]
This other issue is a dupe and has more info: https://github.com/AdobeDocs/commerce-frontend-core/issues/68. Closing.
