### ISSUE TITLE
_extend or _extends?

### ISSUE THREAD

**Issue by sayedMurtadha** [AdobeDocs/commerce-frontend-core#75]
Issue in /src/pages/guide/css/quickstart/customize-styles.md

In the Docs, it is written that the proper way to extend the style is to create an `_extend.less` file in the theme. However, when looking at Magento implementation, there is `_extends.less` file (with 's'). Is this an error in the Docs? Or it works using both file names?
Also, if it does, please mention that since it is confusing.

**Comment by dobooth** [comment]
Found on web: The _extends.less with an S at the end within the Blank Theme, is a file where they created all the classes that can be extended via LESS later within the theme, without the need of creating new components or modular structure for style changes. 

The _extend.less without the S at the end, is for when you are 99% happy with what the parent theme has and you just need to change a couple of things, change some styling and that's it.
