### ISSUE TITLE
Add custom favicons manually

### ISSUE THREAD

**Issue by Sarfarazalis** [AdobeDocs/commerce-frontend-core#82]
[Issue in /src/pages/guide/themes/favicon.md](https://developer.adobe.com/commerce/frontend-core/guide/themes/favicon/)
Add custom favicons manually This is Not working its Load Magento Default version of fav icon,
I have checked after implement the change my Custom icon is visible in the console but it give first priority to vendor module even after overiding.

https://i.imgur.com/s729HZD.png This for reference my custom favicon is called but it take Magento Default icon.

Can you update us

Regards,

Ali

**Comment by hguthrie** [comment]
Hi, thanks for pointing this out. Did you flush the cache after adding the custom favicon? Let us know if that works, in the meantime, I will add this to our backlog for review.

**Comment by jeff-matthews** [comment]
Closing due to lack of response.
