### ISSUE TITLE
Link to LiveReload Extensions is timing out.

### ISSUE THREAD

**Issue by kallie-e** [AdobeDocs/commerce-frontend-core#83]
Issue in /src/pages/guide/tools/grunt.md

On this page:
[https://developer.adobe.com/commerce/frontend-core/guide/tools/grunt/](https://developer.adobe.com/commerce/frontend-core/guide/tools/grunt/)  
  
In the Section titled "Install and configure Grunt", under Step 5, there is a reference to the [LiveReload extension](http://livereload.com/extensions/).   At time of typing this, that page times out.  Perhaps is there a new link that needs to be referenced here?

**Comment by dobooth** [comment]
Yup...seems like the site has been down for some time. The npm library resolves though.
